window.PERSONAJES = [
  { id: "naruto", nombre: "Naruto Uzumaki", equipos: ["equipo7"], aldea: "Konoha", rol: "Hokage", img: "naruto-uzumaki.jpg" },
  { id: "sasuke", nombre: "Sasuke Uchiha", equipos: ["equipo7"], aldea: "Konoha", rol: "Ninja renegado", img: "sasuke-uchiha.jpg" },
  { id: "sakura", nombre: "Sakura Haruno", equipos: ["equipo7"], aldea: "Konoha", rol: "Kunoichi", img: "sakura-haruno.jpg" },
  { id: "kakashi", nombre: "Kakashi Hatake", equipos: ["equipo7", "anbu", "sensei"], aldea: "Konoha", rol: "Sensei · Antiguo Capitán ANBU", img: "kakashi-hatake.jpg" },
  { id: "shikamaru", nombre: "Shikamaru Nara", equipos: ["equipo3"], aldea: "Konoha", rol: "Genin", img: "shikamaru-nara.jpg" },
  { id: "choji", nombre: "Choji Akimichi", equipos: ["equipo3"], aldea: "Konoha", rol: "Genin", img: "choji-akimichi.jpg" },
  { id: "ino", nombre: "Ino Yamanaka", equipos: ["equipo3"], aldea: "Konoha", rol: "Genin", img: "ino-yamanaka.jpg" },
  { id: "neji", nombre: "Neji Hyūga", equipos: ["equipo-guy"], aldea: "Konoha", rol: "Genin · Byakugan", img: "neji-hyuga.jpg" },
  { id: "asuma", nombre: "Asuma Sarutobi", equipos: ["equipo3"], aldea: "Konoha", rol: "Jōnin - Líder", img: "asuma-sarutobi.jpg" },
  { id: "kurenai", nombre: "Kurenai Yūhi", equipos: ["equipo8"], aldea: "Konoha", rol: "Jōnin - Líder · Genjutsu", img: "kurenai-yuuhi.jpg" },
  { id: "hinata", nombre: "Hinata Hyūga", equipos: ["equipo8"], aldea: "Konoha", rol: "Genin · Byakugan", img: "hinata-hyuga.jpg" },
  { id: "kiba", nombre: "Kiba Inuzuka", equipos: ["equipo8"], aldea: "Konoha", rol: "Genin · Rastreo con Akamaru", img: "kiba-inuzuka.jpg" },
  { id: "shino", nombre: "Shino Aburame", equipos: ["equipo8"], aldea: "Konoha", rol: "Genin · Kikaichū", img: "shino-aburame.jpg" },
  { id: "might-guy", nombre: "Might Guy", equipos: ["equipo-guy"], aldea: "Konoha", rol: "Jōnin - Líder · Taijutsu", img: "might-guy.jpg" },
  { id: "rock-lee", nombre: "Rock Lee", equipos: ["equipo-guy"], aldea: "Konoha", rol: "Genin", img: "rock-lee.jpg" },
  { id: "tenten", nombre: "Tenten", equipos: ["equipo-guy"], aldea: "Konoha", rol: "Genin", img: "tenten.jpg" },
  { id: "itachi", nombre: "Itachi Uchiha", equipos: ["akatsuki", "anbu"], aldea: "Konoha", rol: "Antiguo Capitán ANBU de Konoha", img: "itachi-uchiha.jpg" },
  { id: "yamato", nombre: "Yamato", equipos: ["anbu"], aldea: "Konoha", rol: "ANBU de Konoha (nombre clave Tenzo)", img: "yamato.jpg" },
  { id: "danzo", nombre: "Danzo Shimura", equipos: ["anbu", "konoha"], aldea: "Konoha", rol: "Antiguo Líder de Raíz", img: "danzo.jpg" },
  { id: "orochimaru", nombre: "Orochimaru", equipos: ["anbu", "konoha", "legendarios"], aldea: "Konoha", rol: "Antiguo miembro de Raíz · Legendary", img: "orochimaru.jpg" },
  { id: "sai", nombre: "Sai", equipos: ["anbu", "konoha", "equipo7"], aldea: "Konoha", rol: "Antiguo miembro de Raíz", img: "sai.jpg" },
  { id: "ibiki", nombre: "Ibiki Morino", equipos: ["anbu", "konoha"], aldea: "Konoha", rol: "Líder de Tortura e Interrogación", img: "ibiki-morino.jpg" },
  { id: "kisame", nombre: "Kisame Hoshigaki", equipos: ["akatsuki", "anbu"], aldea: "Kirigakure", rol: "Ninja Cazador (ANBU de Kirigakure)", img: "kisame-hoshigaki.jpg" },
  { id: "konan", nombre: "Konan", equipos: ["akatsuki"], aldea: "Amegakure", rol: "Miembro Akatsuki", img: "konan.jpg" },
  { id: "deidara", nombre: "Deidara", equipos: ["akatsuki"], aldea: "Iwagakure", rol: "Miembro Akatsuki", img: "deidara.jpg" },
  { id: "sasori", nombre: "Sasori", equipos: ["akatsuki"], aldea: "Sunagakure", rol: "Miembro Akatsuki", img: "sasori.jpg" },
  { id: "hidan", nombre: "Hidan", equipos: ["akatsuki"], aldea: "Yugakure", rol: "Miembro Akatsuki", img: "hidan.jpg" },
  { id: "kakuzu", nombre: "Kakuzu", equipos: ["akatsuki"], aldea: "Takigakure", rol: "Miembro Akatsuki", img: "kakuzu.jpg" },
  { id: "obito", nombre: "Obito Uchiha", equipos: ["akatsuki"], aldea: "Konoha", rol: "Miembro Akatsuki", img: "obito-uchiha.jpg" },
  { id: "tobi", nombre: "Tobi", equipos: ["akatsuki"], aldea: "Konoha", rol: "Miembro Akatsuki", img: "tobi.jpg" },
  { id: "zetsu", nombre: "Zetsu", equipos: ["akatsuki"], aldea: "Desconocida", rol: "Miembro Akatsuki", img: "zetsu.jpg" },
  { id: "kabuto", nombre: "Kabuto Yakushi", equipos: ["akatsuki", "konoha"], aldea: "Konoha", rol: "Ninja renegado", img: "kabuto-yakushi.jpg" },
  { id: "nagato", nombre: "Nagato", equipos: ["akatsuki"], aldea: "Amegakure", rol: "Miembro Akatsuki", img: "nagato.jpg" },
  { id: "yahiko", nombre: "Yahiko", equipos: ["akatsuki"], aldea: "Amegakure", rol: "Miembro Akatsuki", img: "yahiko.jpg" },
  { id: "karin", nombre: "Karin", equipos: ["akatsuki"], aldea: "Kusagakure", rol: "Kunoichi", img: "karin.jpg" },
  { id: "fu", nombre: "Fu", equipos: ["akatsuki"], aldea: "Takigakure", rol: "Miembro Akatsuki", img: "fu.jpg" },
  { id: "hashirama", nombre: "Hashirama Senju", equipos: ["hokage"], aldea: "Konoha", rol: "Primer Hokage", img: "hashirama-senju.jpg" },
  { id: "tobirama", nombre: "Tobirama Senju", equipos: ["hokage"], aldea: "Konoha", rol: "Segundo Hokage", img: "tobirama-senju.jpg" },
  { id: "hiruzen", nombre: "Hiruzen Sarutobi", equipos: ["hokage"], aldea: "Konoha", rol: "Tercer Hokage", img: "hiruzen-sarutobi.jpg" },
  { id: "minato", nombre: "Minato Namikaze", equipos: ["hokage"], aldea: "Konoha", rol: "Cuarto Hokage", img: "minato-namikaze.jpg" },
  { id: "tsunade", nombre: "Tsunade", equipos: ["hokage", "konoha", "legendarios"], aldea: "Konoha", rol: "Quinta Hokage · Legendary", img: "tsunade.jpg" },
  { id: "gaara", nombre: "Gaara", equipos: ["arena"], aldea: "Sunagakure", rol: "Kazekage", img: "gaara.jpg" },
  { id: "temari", nombre: "Temari", equipos: ["arena"], aldea: "Sunagakure", rol: "Kunoichi", img: "temari.jpg" },
  { id: "kankuro", nombre: "Kankuro", equipos: ["arena"], aldea: "Sunagakure", rol: "Ninja", img: "kankuro.jpg" },
  { id: "chiyo", nombre: "Chiyo", equipos: ["arena"], aldea: "Sunagakure", rol: "Anciana", img: "chiyo-baigyo.jpg" },
  { id: "jiraiya", nombre: "Jiraiya", equipos: ["konoha", "sensei", "legendarios"], aldea: "Konoha", rol: "Sannin · Legendary", img: "jiraiya.jpg" },
  { id: "iruka", nombre: "Iruka Umino", equipos: ["sensei", "konoha"], aldea: "Konoha", rol: "Sensei", img: "iruka-umino.jpg" },
  { id: "ebisu", nombre: "Ebisu", equipos: ["sensei", "konoha"], aldea: "Konoha", rol: "Jōnin · Maestro de Shurikenjutsu", img: "ebisu.jpg" },
  { id: "genma", nombre: "Genma Shiranui", equipos: ["konoha"], aldea: "Konoha", rol: "Jōnin", img: "genma.jpg" },
  { id: "fugaku", nombre: "Fugaku Uchiha", equipos: ["konoha"], aldea: "Konoha", rol: "Líder del clan Uchiha", img: "fugaku-uchiha.jpg" },
  { id: "sakumo", nombre: "Sakumo Hatake", equipos: ["konoha"], aldea: "Konoha", rol: "Jōnin", img: "sakumo-hatake.jpg" },
  { id: "kawaki", nombre: "Kawaki", equipos: ["konoha"], aldea: "Konoha", rol: "Genin", img: "kawaki.jpg" },
  { id: "kurama", nombre: "Kurama", equipos: ["konoha"], aldea: "Konoha", rol: "Bestia con cola · Jinchūriki de Naruto", img: "kurama.jpg" }
];
