window.PERSONAJES = [
  { id: "naruto", nombre: "Naruto Uzumaki", equipo: "equipo7", aldea: "Konoha", rol: "Hokage", img: "naruto-uzumaki.jpg" },
  { id: "sasuke", nombre: "Sasuke Uchiha", equipo: "equipo7", aldea: "Konoha", rol: "Ninja renegado", img: "sasuke-uchiha.jpg" },
  { id: "sakura", nombre: "Sakura Haruno", equipo: "equipo7", aldea: "Konoha", rol: "Kunoichi", img: "sakura-haruno.jpg" },
  { id: "kakashi", nombre: "Kakashi Hatake", equipo: "equipo7", aldea: "Konoha", rol: "Sensei", img: "kakashi-hatake.jpg" },
  { id: "shikamaru", nombre: "Shikamaru Nara", equipo: "equipo8", aldea: "Konoha", rol: "Genin", img: "shikamaru-nara.jpg" },
  { id: "shino", nombre: "Shino Aburame", equipo: "equipo8", aldea: "Konoha", rol: "Genin", img: "shino-aburame.jpg" },
  { id: "hinata", nombre: "Hinata Hyuga", equipo: "equipo8", aldea: "Konoha", rol: "Genin", img: "hinata-hyuga.jpg" },
  { id: "neji", nombre: "Neji Hyuga", equipo: "equipo8", aldea: "Konoha", rol: "Genin", img: "neji-hyuga.jpg" },
  { id: "itachi", nombre: "Itachi Uchiha", equipo: "akatsuki", aldea: "Konoha", rol: "Miembro Akatsuki", img: "itachi-uchiha.jpg" },
  { id: "kisame", nombre: "Kisame Hoshigaki", equipo: "akatsuki", aldea: "Kirigakure", rol: "Miembro Akatsuki", img: "kisame-hoshigaki.jpg" },
  { id: "hiruzen", nombre: "Hiruzen Sarutobi", equipo: "hokage", aldea: "Konoha", rol: "Tercer Hokage", img: "hiruzen-sarutobi.jpg" },
  { id: "asuma", nombre: "Asuma Sarutobi", equipo: "equipo8", aldea: "Konoha", rol: "Jonin", img: "asuma-sarutobi.jpg" },
  { id: "jiraiya", nombre: "Jiraiya", equipo: "konoha", aldea: "Konoha", rol: "Sannin", img: "jiraiya.jpg" },
  { id: "tsunade", nombre: "Tsunade", equipo: "konoha", aldea: "Konoha", rol: "Quinta Hokage", img: "tsunade.jpg" },
  { id: "orochimaru", nombre: "Orochimaru", equipo: "konoha", aldea: "Konoha", rol: "Sannin", img: "orochimaru.jpg" },
  { id: "gaara", nombre: "Gaara", equipo: "arena", aldea: "Sunagakure", rol: "Kazekage", img: "gaara.jpg" },
  { id: "temari", nombre: "Temari", equipo: "arena", aldea: "Sunagakure", rol: "Kunoichi", img: "temari.jpg" },
  { id: "kankuro", nombre: "Kankuro", equipo: "arena", aldea: "Sunagakure", rol: "Ninja", img: "kankuro.jpg" },
  { id: "rock-lee", nombre: "Rock Lee", equipo: "equipo6", aldea: "Konoha", rol: "Genin", img: "rock-lee.jpg" },
  { id: "tenten", nombre: "Tenten", equipo: "equipo6", aldea: "Konoha", rol: "Genin", img: "tenten.jpg" },
  { id: "might-guy", nombre: "Might Guy", equipo: "equipo6", aldea: "Konoha", rol: "Jonin", img: "might-guy.jpg" },
  { id: "choji", nombre: "Choji Akimichi", equipo: "equipo8", aldea: "Konoha", rol: "Genin", img: "choji-akimichi.jpg" },
  { id: "ino", nombre: "Ino Yamanaka", equipo: "equipo8", aldea: "Konoha", rol: "Genin", img: "ino-yamanaka.jpg" },
  { id: "kiba", nombre: "Kiba Inuzuka", equipo: "equipo8", aldea: "Konoha", rol: "Genin", img: "kiba-inuzuka.jpg" },
  { id: "yamato", nombre: "Yamato", equipo: "equipo6", aldea: "Konoha", rol: "ANBU", img: "yamato.jpg" },
  { id: "sai", nombre: "Sai", equipo: "equipo7", aldea: "Konoha", rol: "Genin", img: "sai.jpg" },
  { id: "konan", nombre: "Konan", equipo: "akatsuki", aldea: "Amegakure", rol: "Miembro Akatsuki", img: "konan.jpg" },
  { id: "deidara", nombre: "Deidara", equipo: "akatsuki", aldea: "Iwagakure", rol: "Miembro Akatsuki", img: "deidara.jpg" },
  { id: "sasori", nombre: "Sasori", equipo: "akatsuki", aldea: "Sunagakure", rol: "Miembro Akatsuki", img: "sasori.jpg" },
  { id: "hidan", nombre: "Hidan", equipo: "akatsuki", aldea: "Yugakure", rol: "Miembro Akatsuki", img: "hidan.jpg" },
  { id: "kakuzu", nombre: "Kakuzu", equipo: "akatsuki", aldea: "Takigakure", rol: "Miembro Akatsuki", img: "kakuzu.jpg" },
  { id: "obito", nombre: "Obito Uchiha", equipo: "akatsuki", aldea: "Konoha", rol: "Miembro Akatsuki", img: "obito-uchiha.jpg" },
  { id: "tobi", nombre: "Tobi", equipo: "akatsuki", aldea: "Konoha", rol: "Miembro Akatsuki", img: "tobi.jpg" },
  { id: "zetsu", nombre: "Zetsu", equipo: "akatsuki", aldea: "Desconocida", rol: "Miembro Akatsuki", img: "zetsu.jpg" },
  { id: "minato", nombre: "Minato Namikaze", equipo: "hokage", aldea: "Konoha", rol: "Cuarto Hokage", img: "minato-namikaze.jpg" },
  { id: "hashirama", nombre: "Hashirama Senju", equipo: "hokage", aldea: "Konoha", rol: "Primer Hokage", img: "hashirama-senju.jpg" },
  { id: "tobirama", nombre: "Tobirama Senju", equipo: "hokage", aldea: "Konoha", rol: "Segundo Hokage", img: "tobirama-senju.jpg" },
  { id: "kabuto", nombre: "Kabuto Yakushi", equipo: "akatsuki", aldea: "Konoha", rol: "Ninja renegado", img: "kabuto-yakushi.jpg" },
  { id: "danzo", nombre: "Danzo Shimura", equipo: "konoha", aldea: "Konoha", rol: "Líder ANBU", img: "danzo.jpg" },
  { id: "iruka", nombre: "Iruka Umino", equipo: "konoha", aldea: "Konoha", rol: "Sensei", img: "iruka-umino.jpg" },
  { id: "ebisu", nombre: "Ebisu", equipo: "konoha", aldea: "Konoha", rol: "Jonin", img: "ebisu.jpg" },
  { id: "genma", nombre: "Genma Shiranui", equipo: "konoha", aldea: "Konoha", rol: "Jonin", img: "genma.jpg" },
  { id: "ibiki", nombre: "Ibiki Morino", equipo: "konoha", aldea: "Konoha", rol: "Jonin", img: "ibiki-morino.jpg" },
  { id: "fugaku", nombre: "Fugaku Uchiha", equipo: "konoha", aldea: "Konoha", rol: "Líder Uchiha", img: "fugaku-uchiha.jpg" },
  { id: "sakumo", nombre: "Sakumo Hatake", equipo: "konoha", aldea: "Konoha", rol: "Jonin", img: "sakumo-hatake.jpg" },
  { id: "tenzo", nombre: "Tenzo", equipo: "konoha", aldea: "Konoha", rol: "ANBU", img: "tenzo.jpg" },
  { id: "chiyo", nombre: "Chiyo", equipo: "arena", aldea: "Sunagakure", rol: "Anciana", img: "chiyo-baigyo.jpg" },
  { id: "karin", nombre: "Karin", equipo: "akatsuki", aldea: "Kusagakure", rol: "Kunoichi", img: "karin.jpg" },
  { id: "kawaki", nombre: "Kawaki", equipo: "konoha", aldea: "Konoha", rol: "Genin", img: "kawaki.jpg" },
  { id: "nagato", nombre: "Nagato", equipo: "akatsuki", aldea: "Amegakure", rol: "Miembro Akatsuki", img: "nagato.jpg" },
  { id: "yahiko", nombre: "Yahiko", equipo: "akatsuki", aldea: "Amegakure", rol: "Miembro Akatsuki", img: "yahiko.jpg" },
  { id: "fu", nombre: "Fu", equipo: "akatsuki", aldea: "Takigakure", rol: "Miembro Akatsuki", img: "fu.jpg" },
  { id: "kurama", nombre: "Kurama", equipo: "konoha", aldea: "Konoha", rol: "Bestia con cola", img: "kurama.jpg" }
];
